//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daisy.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Daisy.App_GlobalResources.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is where i write a little bit about myself just because i need to fill this spot.
        /// </summary>
        public static string AboutContentHeader {
            get {
                return ResourceManager.GetString("AboutContentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string ContactDivGithub {
            get {
                return ResourceManager.GetString("ContactDivGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn.
        /// </summary>
        public static string ContactDivLinkedIn {
            get {
                return ResourceManager.GetString("ContactDivLinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string ContactDivResume {
            get {
                return ResourceManager.GetString("ContactDivResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ContactDivSendEmail {
            get {
                return ResourceManager.GetString("ContactDivSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am a 2B Computer Engineering student at University of Waterloo. I see myself as a creative and hardworking individual. I enjoy running cross country and sketching on my free time. &lt;a href=&quot;About.aspx&quot;&gt;More... &lt;/a&gt;.
        /// </summary>
        public static string HomeContentBoxAboutContent {
            get {
                return ResourceManager.GetString("HomeContentBoxAboutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string HomeContentBoxAboutTitle {
            get {
                return ResourceManager.GetString("HomeContentBoxAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s talk! Send me a message and I&apos;d love to chat..
        /// </summary>
        public static string HomeContentBoxContactContent {
            get {
                return ResourceManager.GetString("HomeContentBoxContactContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string HomeContentBoxContactTitle {
            get {
                return ResourceManager.GetString("HomeContentBoxContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have been drawing ever since I remember, check out some of my best work &lt;a href=&quot;Illustrations.aspx&quot;&gt;here! &lt;/a&gt;.
        /// </summary>
        public static string HomeContentBoxPicsContent {
            get {
                return ResourceManager.GetString("HomeContentBoxPicsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illustrations.
        /// </summary>
        public static string HomeContentBoxPicsTitle {
            get {
                return ResourceManager.GetString("HomeContentBoxPicsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have been exposed to programming in 2010 and ever since I have building upon my knowledge. Check out my &lt;a href=&quot;Resume.aspx&quot;&gt;Resume&lt;/a&gt; to learn more! .
        /// </summary>
        public static string HomeContentBoxWebContent {
            get {
                return ResourceManager.GetString("HomeContentBoxWebContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web &amp; Software Knowledge.
        /// </summary>
        public static string HomeContentBoxWebTitle {
            get {
                return ResourceManager.GetString("HomeContentBoxWebTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software &amp; Web Developer.
        /// </summary>
        public static string HomeHeaderDescriptionTitle {
            get {
                return ResourceManager.GetString("HomeHeaderDescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oksana Zvarych.
        /// </summary>
        public static string HomeHeaderNameTitle {
            get {
                return ResourceManager.GetString("HomeHeaderNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Out More.
        /// </summary>
        public static string HomePrimaryContentHeader {
            get {
                return ResourceManager.GetString("HomePrimaryContentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oksana Zvarych © 2014 | All Rights Reserved.
        /// </summary>
        public static string NavFooterDescription {
            get {
                return ResourceManager.GetString("NavFooterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string NavMenuAbout {
            get {
                return ResourceManager.GetString("NavMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string NavMenuContact {
            get {
                return ResourceManager.GetString("NavMenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string NavMenuHome {
            get {
                return ResourceManager.GetString("NavMenuHome", resourceCulture);
            }
        }
    }
}
